### ISSUE TITLE
Unable to get facets

### ISSUE THREAD

**Issue by bonndan** [dedica-team/nivio#424]
```
8.2.2021 16:45:262021-02-08 15:45:26.362  WARN 1 --- [nio-8080-exec-9] de.bonndan.nivio.search.SearchIndex      : Unable to get the facets for the given query error:
8.2.2021 16:45:26
8.2.2021 16:45:26org.apache.lucene.index.IndexNotFoundException: no segments* file found in RAMDirectory@67763e1c lockFactory=org.apache.lucene.store.SingleInstanceLockFactory@482bd4b2: files: []
8.2.2021 16:45:26	at org.apache.lucene.index.SegmentInfos$FindSegmentsFile.run(SegmentInfos.java:715) ~[lucene-core-8.7.0.jar!/:8.7.0 2dc63e901c60cda27ef3b744bc554f1481b3b067 - atrisharma - 2020-10-29 19:35:28]
8.2.2021 16:45:26	at org.apache.lucene.index.StandardDirectoryReader.open(StandardDirectoryReader.java:81) ~[lucene-core-8.7.0.jar!/:8.7.0 2dc63e901c60cda27ef3b744bc554f1481b3b067 - atrisharma - 2020-10-29 19:35:28]
8.2.2021 16:45:26	at org.apache.lucene.index.DirectoryReader.open(DirectoryReader.java:63) ~[lucene-core-8.7.0.jar!/:8.7.0 2dc63e901c60cda27ef3b744bc554f1481b3b067 - atrisharma - 2020-10-29 19:35:28]
```

probably related to #423 breaking indexing

**Comment by bonndan** [comment]
Happens when uncaught exceptions are thrown during indexing.
